### ISSUE TITLE
Question: how to render in browser

### ISSUE THREAD

**Issue by olimart** [leungwensen/xmind-sdk-javascript#7]
Hi,
How to render drawn canvas in HTML page?

**Comment by leungwensen** [comment]
`xmind-sdk-javascript` is to extract the file structure of an XMind file, getting it rendered is a whole other story.

To render an XMind file (which is a hierarchy structure, or, more commonly called `a tree`) in browser, what you need to do is:

1. apply a tree layout algorithm. 
2. draw it.

Applying a tree layout algorithm is to distribute appropriate positions in a canvas for each nodes in the tree. The most popular solution is `d3-hierarchy`, a more suitable one for XMind-like MindMaps is `mindmap-layouts`.

Drawing a tree with position info in browsers is easy, and you have a lot of options. You can draw it with  HTML5 canvas, SVG, or libraries of upper levels like `d3`, `raphael`,`Snap.svg`, etc.

But if what you asking is `how to develop an app just like XMind which runs in the browsers`, I have to say, you have a long long way to go.

**Comment by olimart** [comment]
Thanks for the clarification. I better understand the purpose of this project now.

> But if what you asking is how to develop an app just like XMind which runs in the browsers, I have to say, you have a long long way to go.

Indeed 😄
